c_compiler_version:
  - 11

cxx_compiler_version:
  - 11

cuda_compiler:
  - cuda-nvcc

cuda11_compiler:
  - nvcc

cmake_version:
  - ">=3.26.4"

scikit_build_version:
  - ">=0.13.1"

sysroot_version:
  - "2.17"
