# Copyright (c) 2019-2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libwholegraph-split

source:
  git_url: ../../..

build:
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - BUILD_ABI
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=libwholegraph-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libwholegraph-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS

# Here we duplicate the dependencies so conda will populate both _build_env
# and _h_env_placeholder directories. This is needed to run clang-tidy.
# We need both build and host, or conda will only use _h_env_placeholder
# directory, which is removed after a build. Having only _build_env is not
# enough as CMake will not search for dependencies in this directory.
# This needs to be removed once CI support from sources builds
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake_version }}
    - cudatoolkit ={{ cuda_version }}
    - libraft-headers ={{ minor_version }}
    - librmm ={{ minor_version }}
    - ninja
    - nccl
    - doxygen =1.8.20
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cmake {{ cmake_version }}
    - cuda-nvtx ={{ cuda_version }}
    - cudatoolkit ={{ cuda_version }}
    - libraft-headers ={{ minor_version }}
    - librmm ={{ minor_version }}

outputs:
  - name: libwholegraph
    version: {{ version }}
    script: install_libwholegraph.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - libraft-headers ={{ minor_version }}
        - librmm ={{ minor_version }}
        - nccl
    about:
      home: https://rapids.ai/
      summary: libwholegraph library
  - name: libwholegraph-tests
    version: {{ version }}
    script: install_libwholegraph_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - {{ pin_subpackage('libwholegraph', exact=True) }}
    about:
      home: https://rapids.ai/
      summary: libwholegraph tests
